[package]
name = "event_store-eventbus-inmemory"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid.workspace = true
serde.workspace = true
actix.workspace = true
futures.workspace = true
tokio.workspace = true

async-stream.workspace = true

event_store-core.workspace = true

[dev-dependencies]
test-log.workspace = true
test-span.workspace = true
tracing-subscriber.workspace = true
