[workspace]
members = [
	".",
	"chekov_macros",
	"event_store",
	"examples/*"
]

[package]
name = "chekov"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/freyskeyd/chekov"
documentation = "https://docs.rs/chekov"
description = "CQRS/ES Framework"
edition = "2018"
keywords = []
categories = []
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]

[dependencies]
event_store = { version = "0.1.0", path = "event_store" }
chekov_macros = { version = "0.1.0", path = "chekov_macros" }
fnv = "1.0.3"
chrono = "0.4"
uuid = { version = "0.8", features = ["serde", "v4"] }
sqlx = {version = "0.4.1", features = ["postgres", "chrono", "time", "uuid", "json", "offline"]}
async-trait = "0.1"
serde = "*"
serde_json = "*"
actix = "*"
futures = "*"
log = {version = "0.4"}
actix-interop = { git = "https://github.com/Diggsey/actix-interop" }


tracing = "0.1"
tracing-futures = { version = "*" }

inventory = "*"
lazy_static = "1.4.0"
