[package]
name = "event_store"
version = "0.1.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]
edition = "2018"
description = "Crate to deal with every aspect of an eventstore"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1"
tokio = {version = "0.3", features = ["rt", "sync", "time", "stream", "macros"]}
futures = "0.3"
log = {version = "0.4"}
actix = "*"
sqlx = {version = "0.4.1", features = ["postgres", "chrono", "time", "uuid", "json", "offline", "runtime-actix-native-tls"]}
chrono = "0.4"
actix-interop = { git = "https://github.com/Diggsey/actix-interop" }

tracing = "0.1"
tracing-futures = { version = "*" }

[dev-dependencies]
actix-rt = "1.1"
pretty_assertions = "0.6.1"

[features]
verbose = []
