[package]
name = "event_store"
version = "0.1.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]
edition = "2018"
description = "Crate to deal with every aspect of an eventstore"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = "1.0"
serde_json = "1.0"
async-trait = "0.1.36"
tokio = {version = "0.2", features = ["time", "stream", "macros", "rt-threaded"]}
futures = "0.3"
log = {version = "0.4"}
actix = "0.10.0-alpha.3"
sqlx = {version = "0.4.0-beta.1", features = ["postgres", "chrono", "time", "uuid", "json", "offline"]}
chrono = "0.4"

[dev-dependencies]
actix-rt = "1.1"
pretty_assertions = "0.6.1"

[features]
verbose = []
