[package]
name = "event_store"
version = "0.1.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = "*"
serde_json = "*"
async-trait = "0.1.36"
tokio = {version = "*", features = ["time", "stream", "macros", "rt-threaded"]}
futures = "0.3"
log = {version = "0.4"}
actix = "0.10.0-alpha.3"

[dev-dependencies]
rust_decimal = { version = "*", features = ["serde-float"] }

[features]
verbose = []
