[package]
name = "bank"
version = "0.1.0"
authors = ["Freyskeyd <simon.paitrault@gmail.com>"]
edition = "2018"
workspace = "../../"

[dependencies]
event_store = { path = "../../event_store", features = ["verbose"] }
chekov = { path = "../../"  }
tokio = {version = "0.3", features = ["macros", "rt"]}
uuid = { version = "0.8", features = ["serde", "v4"] }
serde = "*"
serde_json = "*"
actix = "*"
actix-rt = "1.1"
log = "*"
futures = "*"
actix-web = "3"

sqlx = {version = "0.4.1", features = ["postgres", "chrono", "time", "uuid", "json"]}
chrono = "0.4"

tracing = {version ="*", features = []}
tracing-subscriber = "*"
tracing-futures = "*"
tracing-log = "*"

inventory = "*"
lazy_static = "*"
