[package]
name = "bank"
version = "0.1.0"
workspace = "../../"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

chekov = { path = "../../crates/chekov"  }
actix-web.workspace = true
tracing-subscriber.workspace = true
