[package]
name = "gift_shop"
version = "0.1.0"
workspace = "../../"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
tokio.workspace = true
sqlx.workspace = true
actix.workspace = true

chekov = { path = "../../crates/chekov"  }
actix-web.workspace = true
tracing-subscriber.workspace = true
