[package]
name = "event_store-eventbus-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid.workspace = true
serde.workspace = true
sqlx = { workspace = true, features = ["postgres"] }
futures.workspace = true

event_store-core = { version = "0.1.0", path = "../event_store-core" }
