on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: docker compose -f scripts/tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - name: Run cargo check
        run: cargo check --all

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: docker compose -f scripts/tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - name: Run cargo test
        run: cargo test --all

  doc:
    name: Doc - build the documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - run: docker compose -f scripts/tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - run: cargo doc --no-deps --all --exclude bank
      - uses: actions/upload-artifact@v4
        with:
          name: doc
          path: target/doc

  publish:
    name: Publish
    needs: [doc, check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Download doc
        uses: actions/download-artifact@v4
        with:
          name: doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - uses: taiki-e/install-action@cargo-llvm-cov

      - run: docker compose -f scripts/tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - name: Generate coverage report
        run: cargo llvm-cov --all-features --workspace --exclude bank --exclude gift_shop --no-fail-fast --lcov --output-path lcov.info

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          github-token: ${{ secrets.github_token }}
          file: lcov.info
