on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true


      - run: docker-compose -f tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/event_store
        with:
          command: check
          args: --all

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: docker-compose -f tests/docker-compose.yml run -d -p 5432:5432 postgres
      - run: sleep 10

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/event_store
        with:
          command: test
          args: --all

  # coverage:
  #   name: Coverage
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v2

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: nightly
  #         override: true

  #     - run: docker-compose -f tests/docker-compose.yml run -d -p 5432:5432 postgres
  #     - run: sleep 10

  #     - uses: actions-rs/cargo@v1
  #       with:
  #         command: test
  #         args: --all-features --no-fail-fast --all
  #       env:
  #         DATABASE_URL: postgresql://postgres:postgres@localhost:5432/event_store
  #         CARGO_INCREMENTAL: '0'
  #         RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
  #         RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'

  #     - id: coverage
  #       uses: actions-rs/grcov@v0.1

  #     - name: Coveralls GitHub Action
  #       uses: coverallsapp/github-action@v1.1.1
  #       with:
  #         github-token: ${{ secrets.github_token }}
  #         path-to-lcov: ${{ steps.coverage.outputs.report }}
